app:
  cache:
    ttl-seconds: 3600  # 1 hour redis TTL for PSP result cache
  kafka:
    concurrency:
      journal-entries: 3
      capture-commands: 3
      capture-submitted: 3


server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/tomcat
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D'
      buffered: true

spring:
  application:
    name: payment-consumers
  lifecycle:
    timeout-per-shutdown-phase: 45s
  jackson:
    time-zone: UTC
  datasource:
    payment-consumers:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: ${spring.application.name}-PaymentConsumerHikariPool
    account-snapshot-job:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: ${spring.application.name}-AccountSnapshotHikariPool


  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog.central.xml

management:
  server:
    port: 9000
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
      show-details: always

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dogancaglar.common.db.entity
  type-handlers-package: com.dogancaglar.common.db.typehandler

psp:
  gateway:
    type: SIMULATED
  refund:
    simulation:
      scenarios:
        NORMAL:
          timeouts:
            enabled: true
            probability: 0
          latency:
            fast:
              probability: 100
              minMs: 50
              maxMs: 150
            moderate:
              probability: 0
              minMs: 150
              maxMs: 300
            slow:
              probability: 0
              minMs: 300
              maxMs: 600
          response:
            successful: 50
            retryable: 40
            nonRetryable: 10
        PEAK:
          timeouts:
            enabled: true
            probability: 25
          latency:
            fast:
              probability: 30
              minMs: 250
              maxMs: 500
            moderate:
              probability: 50
              minMs: 501
              maxMs: 1500
            slow:
              probability: 20
              minMs: 1501
              maxMs: 2500
          response:
            successful: 50
            retryable: 45
            statusCheck: 0
            nonRetryable: 5
        DEGRADED:
          timeouts:
            enabled: true
            probability: 30
          latency:
            fast:
              probability: 20
              minMs: 2000
              maxMs: 2200
            moderate:
              probability: 20
              minMs: 2201
              maxMs: 2600
            slow:
              probability: 60
              minMs: 2601
              maxMs: 2990
          response:
            successful: 50
            retryable: 40
            statusCheck: 0
            nonRetryable: 10
        BEST_PSP_EVER:
          timeouts:
            enabled: false
            probability: 0
          latency:
            fast:
              probability: 100
              minMs: 1
              maxMs: 2
            moderate:
              probability: 0
              minMs: 0
              maxMs: 0
            slow:
              probability: 0
              minMs: 0
              maxMs: 0
          response:
            successful: 100
            retryable: 0
            statusCheck: 0
            nonRetryable: 0
  capture:
    simulation:
      scenarios:
        NORMAL:
          timeouts:
            enabled: true
            probability: 0
          latency:
            fast:
              probability: 100
              minMs: 50
              maxMs: 150
            moderate:
              probability: 0
              minMs: 150
              maxMs: 300
            slow:
              probability: 0
              minMs: 300
              maxMs: 600
          response:
            successful: 100
            retryable: 0
            nonRetryable: 0
        PEAK:
          timeouts:
            enabled: true
            probability: 25
          latency:
            fast:
              probability: 30
              minMs: 250
              maxMs: 500
            moderate:
              probability: 50
              minMs: 501
              maxMs: 1500
            slow:
              probability: 20
              minMs: 1501
              maxMs: 2500
          response:
            successful: 50
            retryable: 45
            statusCheck: 0
            nonRetryable: 5
        DEGRADED:
          timeouts:
            enabled: true
            probability: 30
          latency:
            fast:
              probability: 20
              minMs: 2000
              maxMs: 2200
            moderate:
              probability: 20
              minMs: 2201
              maxMs: 2600
            slow:
              probability: 60
              minMs: 2601
              maxMs: 2990
          response:
            successful: 50
            retryable: 40
            statusCheck: 0
            nonRetryable: 10
        BEST_PSP_EVER:
          timeouts:
            enabled: false
            probability: 0
          latency:
            fast:
              probability: 100
              minMs: 1
              maxMs: 2
            moderate:
              probability: 0
              minMs: 0
              maxMs: 0
            slow:
              probability: 0
              minMs: 0
              maxMs: 0
          response:
            successful: 100
            retryable: 0
            statusCheck: 0
            nonRetryable: 0

payment:
  processor:
    simulation:
      simulated-merchant-accounts:
        - "ADYEN_MOCK_MERCHANT_NL"
        - "MARKETPLACE-5"
        - "MARKETPLACE_PERF_TEST_EU"
