// Payment API service - Handles payment creation and authorization

const PROXY_URL = import.meta.env.VITE_PROXY_URL || 'http://127.0.0.1:3001';

/**
 * Send payment creation request via backend proxy
 * Returns payment response with paymentIntentId and clientSecret
 * @param {Object} paymentData - Payment request data
 * @param {string} idempotencyKey - Idempotency key for the request (generated by browser)
 */
export async function createPayment(paymentData, idempotencyKey) {
  const url = `${PROXY_URL}/api/checkout/process-payment`;
  
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Idempotency-Key': idempotencyKey
      },
      body: JSON.stringify(paymentData),
    });

    const responseData = await response.json().catch(() => ({}));

    if (!response.ok) {
      const retryAfter = response.headers.get('retry-after');
      throw {
        status: response.status,
        statusText: response.statusText,
        data: {
          ...responseData,
          headers: retryAfter ? { 'retry-after': retryAfter } : {}
        },
        message: responseData.message || responseData.error || `HTTP ${response.status}: ${response.statusText}`,
      };
    }

    // Extract headers from successful response
    const retryAfter = response.headers.get('retry-after');
    const location = response.headers.get('location');
    const idempotentReplayed = response.headers.get('idempotent-replayed');
    
    return {
      payment: responseData.payment || responseData,
      status: response.status,
      headers: {
        ...(retryAfter && { 'retry-after': retryAfter }),
        ...(location && { 'location': location }),
        ...(idempotentReplayed && { 'idempotent-replayed': idempotentReplayed })
      }
    };
  } catch (error) {
    if (error.status) throw error;
    
    throw {
      status: 0,
      statusText: 'Network Error',
      data: {},
      message: error.message || 'Failed to connect to proxy server',
    };
  }
}

/**
 * Poll payment status endpoint to check if client secret is available
 * Used when payment creation returns 202 (pending)
 */
export async function pollPaymentStatus(paymentIntentId, merchantAccount, maxAttempts = 30, intervalMs = 2000) {
  // the proxy calls the payment API as this merchant's backend
  const url = `${PROXY_URL}/api/checkout/payment-status/${paymentIntentId}?merchantAccount=${encodeURIComponent(merchantAccount)}`;
  
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      });

      if (response.ok) {
        const data = await response.json();
        
        if (data.payment?.clientSecret) {
          return {
            payment: data.payment,
            status: 200
          };
        }
      }
      
      // Wait before next attempt
      if (attempt < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, intervalMs));
      }
    } catch (error) {
      if (attempt < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, intervalMs));
      }
    }
  }
  
  throw {
    status: 0,
    statusText: 'Polling Timeout',
    data: {},
    message: 'Payment status polling timed out. Client secret not available after maximum attempts.',
  };
}

/**
 * Authorize a payment intent
 * Called after the Payment Element has collected the card. The card itself went to Stripe only;
 * we send Stripe's PaymentMethod id (pm_...), which payment-service passes to Stripe's confirm.
 * @param {string} paymentIntentId - The internal payment intent ID
 * @param {string|null} paymentMethodId - Stripe PaymentMethod id (pm_...)
 * @param {string} merchantAccount - the merchant the payment is for (the proxy acts as its backend)
 */
export async function authorizePayment(paymentIntentId, paymentMethodId, merchantAccount) {
  // the proxy calls the payment API as this merchant's backend
  const url = `${PROXY_URL}/api/checkout/authorize-payment/${paymentIntentId}?merchantAccount=${encodeURIComponent(merchantAccount)}`;
  const body = paymentMethodId
    ? { paymentMethod: { type: 'CardToken', token: paymentMethodId } }
    : {};

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });

    const responseData = await response.json().catch(() => ({}));
  
    if (!response.ok) {
      throw {
        status: response.status,
        statusText: response.statusText,
        data: responseData,
        message: responseData.message || responseData.error || `HTTP ${response.status}: ${response.statusText}`,
      };
    }

    return {
      payment: responseData.payment || responseData,
      status: response.status
    };
  } catch (error) {
    if (error.status) throw error;
    
    throw {
      status: 0,
      statusText: 'Network Error',
      data: {},
      message: error.message || 'Failed to connect to proxy server',
    };
  }
}
