app:
  instance-id: ${POD_NAME:${HOSTNAME:${random.value}}}
  pod-name: ${POD_NAME}
  edge-cell-base-url: ${EDGE_CELL_BASE_URL}
  edge-cell-headless-service: ${EDGE_CELL_HEADLESS_SERVICE}

  datasource:
    outbox:
      username: ${EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME}
      password: ${EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD}
      maximum-pool-size: 40
      connection-timeout: 15000
      validation-timeout: 15000
      idle-timeout: 600000
      max-lifetime: 1800000
    maintenance:
      username: ${EDGE_DB_MAINTENANCE_USERNAME}
      password: ${EDGE_DB_MAINTENANCE_PASSWORD}
      maximum-pool-size: 1
      minimum-idle: 0
      connection-timeout: 15000
      validation-timeout: 15000
      idle-timeout: 60000
      max-lifetime: 1800000
    central:
      jdbc-url: ${CENTRAL_DB_URL}
      username: ${CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME}
      password: ${CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD}
      maximum-pool-size: 40
      connection-timeout: 15000
      validation-timeout: 15000
      idle-timeout: 600000
      max-lifetime: 1800000

spring:
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}
      timeout: 10s
      lettuce:
        pool:
          max-active: 64
          max-idle: 32
          min-idle: 16
          max-wait: 5000ms

outbox-dispatcher:
  thread-count: 16
  batch-size: 2000
  pool-size: 16

db:
  outbox:
    statement-timeout-ms: 5000
    lock-timeout-ms: 500
    idle-in-tx-timeout-ms: 0


