server:
  port: 8081

spring:
  application:
    name: payment-edge-workers
  jackson:
    time-zone: UTC
  data:
    redis:
  liquibase:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dogancaglar.common.db.entity
  type-handlers-package: com.dogancaglar.common.db.typehandler

management:
  server:
    port: 9001
  health:
    probes:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
      show-details: always


app:
  datasource:
    outbox:
      driver-class-name: org.postgresql.Driver
      pool-name: ${spring.application.name}-edge-outbox-pool
    maintenance:
      driver-class-name: org.postgresql.Driver
      pool-name: ${spring.application.name}-edge-maint-pool
    central:
      driver-class-name: org.postgresql.Driver
      pool-name: ${spring.application.name}-central-writer-pool
