spring:
  profile: local
image:
  repository: dcaglar1987/payment-consumers
  tag: latest
  pullPolicy: Always
resources:
  requests: {cpu: "200m", memory: "700Mi"}
  limits: {memory: "700Mi"}
jvmOpts: >-
  -XX:+UseG1GC -XX:+AlwaysActAsServerClassMachine -XX:+UseStringDeduplication -XX:MaxRAMPercentage=45 -XX:InitialRAMPercentage=45 -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=128m -XX:ThreadStackSize=512 -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=30
service:
  type: ClusterIP
  portName: http
  port: 8080
keda:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.payment.svc.cluster.local:9092
        consumerGroup: psp-capture-executor-consumer-group
        topic: gateway.capture.commands
        lagThreshold: "2400"
        # Ensure you are using the latest version-compliant metadata
        offsetResetPolicy: latest
serviceMonitor:
  enabled: false
  path: /actuator/prometheus
  interval: 15s
  scrapeTimeout: 10s
  scheme: http
  labels:
    release: prometheus-stack
replicaCount: 1
redis:
  url: redis://redis-master:6379
kafka:
  bootstrapServers: kafka.payment.svc.cluster.local:9092
config:
  CENTRAL_DB_URL: "jdbc:postgresql://central-db-postgresql:5432/central-db?options=-c%20timezone=UTC"
  CENTRAL_DB_NAME: "central-db"
