
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: ingress-controller
      additionalLabels:
        release: ignore-me
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
    ports:
      http: 80
      https: 443
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      memory: 1.5Gi
  admissionWebhooks:
    enabled: false
    patch:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          memory: 64Mi
    createSecretJob:
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          memory: 64Mi
  allowSnippetAnnotations: true
  config:
    annotations-risk-level: "Critical"
    lua-shared-dicts: "cell_routing: 1m"
