defaultRules:
  create: false

prometheusOperator:
  resources:
    requests: { cpu: 30m,  memory: 96Mi }
    limits:   { memory: 96Mi }
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tls:
    enabled: false

prometheus:
  prometheusSpec:
    enableAdminAPI: true
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage
    containers:
      - name: config-reloader
        resources:
          requests: { cpu: 5m,  memory: 24Mi }
          limits:   { memory: 24Mi }
    resources:
      requests: { cpu: 150m, memory: 600Mi }
      limits:   { memory: 600Mi }
    retention: 2h
    walCompression: true
    scrapeInterval: 60s
    evaluationInterval: 60s
    serviceMonitorSelector:
      matchLabels:
        release: prometheus-stack
    serviceMonitorNamespaceSelector: {}   # 👈 allow ServiceMonitors from ALL namespaces

alertmanager:
  alertmanagerSpec:
    containers:
      - name: config-reloader
        resources:
          requests: { cpu: 5m,  memory: 24Mi }
          limits:   { memory: 24Mi }
    resources:
      requests: { cpu: 30m, memory: 48Mi }
      limits:   { memory: 48Mi }

grafana:
  defaultDashboardsEnabled: false
  adminPassword: admin
  plugins: []
  readinessProbe:
    timeoutSeconds: 10
    periodSeconds: 30
    failureThreshold: 20
  livenessProbe:
    timeoutSeconds: 10
    periodSeconds: 30
    failureThreshold: 20
  grafana.ini:
    database:
      query_retries: 5
      transaction_retries: 5
      wal: true
  service:
    type: NodePort
    nodePort: 32000
  resources:
    requests: { cpu: 200m, memory: 512Mi }
    limits:   { memory: 1024Mi }
  additionalDataSources:
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.monitoring.svc.cluster.local:3200
      access: proxy
      jsonData:
        httpMethod: GET
        grpc: false
  sidecar:
    datasources:
      exemplarTraceIdDestinations:
        datasourceUid: tempo
        traceIdLabelName: trace_id
      resources:
        requests: { cpu: 5m,  memory: 24Mi }
        limits:   { memory: 24Mi }
    dashboards:
      resources:
        requests: { cpu: 5m,  memory: 24Mi }
        limits:   { memory: 24Mi }

kube-state-metrics:
  resources:
    requests: { cpu: 30m,  memory: 48Mi }
    limits:   { memory: 48Mi }

kubelet:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheusAdapter:
  enabled: false