mode: daemonset
image:
  repository: otel/opentelemetry-collector-contrib

resources:
  limits:
    cpu: 200m
    memory: 456Mi
  requests:
    cpu: 150m
    memory: 128Mi

presets:
  logsCollection:
    enabled: true
  kubernetesAttributes:
    enabled: true
  hostMetrics:
    enabled: false
  kubeletMetrics:
    enabled: false

# Explicitly tell Helm to create a Kubernetes Service even though we are running as a DaemonSet
service:
  enabled: true




config:
  processors:
    batch: {}

  exporters:
    otlphttp/posthog:
      traces_endpoint: "https://eu.i.posthog.com/i/v1/traces"
      headers:
        Authorization: "Bearer phc_ABquVAfZ7ZA3uYgMtd39p83633a5KBRAwTPkSFHTvWYc"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp/posthog]