apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-central-relay.fullname" . }}
  labels:
    {{- include "payment-central-relay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "payment-central-relay.fullname" . }}
  template:
    metadata:
      rollout/reboot: "{{ now | unixEpoch }}"
      labels:
        app: {{ include "payment-central-relay.fullname" . }}
        {{- include "payment-central-relay.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      # Anti-affinity rule to ensure payment-central-relay and payment-consumers are not co-located on the same physical node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - payment-consumers
                topologyKey: "kubernetes.io/hostname"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: payment-central-relay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          envFrom:
          - configMapRef:
              name: payment-central-relay-job-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-central-relay-job-credentials
                  key: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME
            - name: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-central-relay-job-credentials
                  key: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD
            - name: CENTRAL_DB_DUTY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-central-relay-job-credentials
                  key: CENTRAL_DB_DUTY_USERNAME
            - name: CENTRAL_DB_DUTY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-central-relay-job-credentials
                  key: CENTRAL_DB_DUTY_PASSWORD
            - name: CENTRAL_DB_MAINTENANCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-central-relay-job-credentials
                  key: CENTRAL_DB_MAINTENANCE_USERNAME
            - name: CENTRAL_DB_MAINTENANCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-central-relay-job-credentials
                  key: CENTRAL_DB_MAINTENANCE_PASSWORD
          startupProbe:
            httpGet: {path: /actuator/health/liveness, port: management}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: management}
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: management}
            periodSeconds: 15
            failureThreshold: 4
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
