
redis:
  url: redis://redis-master:6379
kafka:
  bootstrapServers: kafka.payment.svc.cluster.local:9092
spring:
  profile: local
serviceMonitor:
  enabled: false
  labels:
    release: prometheus-stack
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s
replicaCount: 1
keda:
  enabled: false
resources:
  requests: {cpu: 200m, memory: 700Mi}
  limits: {memory: 700Mi}
config:
  CENTRAL_DB_URL: "jdbc:postgresql://central-db-postgresql:5432/central-db?options=-c%20timezone=UTC"
