server:
  tomcat:
    threads:
      max: 120
      min-spare: 40
    max-connections: 1000
    accept-count: 200
    connection-timeout: 20000

#app:
  instance-id: ${POD_NAME:${HOSTNAME:${random.value}}}
  payment-service:
    api-key: secretpaymentapikey12345
spring:
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6379}
      timeout: 10s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 5000ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL:http://localhost:8180/realms/payment}

  datasource:
    edge:
      url: ${EDGE_DB_URL}
      username: ${EDGE_DB_PAYMENT_SERVICE_USERNAME}
      password: ${EDGE_DB_PAYMENT_SERVICE_PASSWORD}
      connection-timeout: 5000
      validation-timeout: 1000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-init-sql: "SET statement_timeout = '100ms'; SET lock_timeout = '50ms';"
      maximum-pool-size: 12

outbox-dispatcher:
  thread-count: 1
  batch-size: 300
  pool-size: 1

db:
  web:
    statement-timeout-ms: 500
    lock-timeout-ms: 250
    idle-in-tx-timeout-ms: 0

stripe:
  api:
    api-key: ${STRIPE_API_KEY:sk_test_51ShA8HEAJKUKtoJwTALvrfMadP0eoKwyggnasHkqgY6y6jLoSjg9YqewkxiYrRw54TnZ7tVFX5Xreg3qaHm5wWAX00tupdpr6y}
    connect-timeout: 5000
    read-timeout: 30000

psp:
  gateway:
    type: SIMULATED
  authorization:
    simulation:
      currentScenario: NORMAL
      scenarios:
        NORMAL:
          timeouts:
            enabled: true
            probability: 0
          latency:
            fast:
              probability: 0
              minMs: 100
              maxMs: 300
            moderate:
              probability: 100
              minMs: 300
              maxMs: 500
            slow:
              probability: 0
              minMs: 500
              maxMs: 900
          response:
            successful: 100
            retryable: 0
            statusCheck: 0
            nonRetryable: 0
  refund:
    simulation:
      currentScenario: NORMAL
  capture:
    simulation:
      currentScenario: NORMAL

