spring:
  profile: azure
image:
  repository: dcaglar1987/payment-consumers
  tag: latest
  pullPolicy: Always
resources:
  requests: {cpu: "200m", memory: "1536Mi"}
  limits: {memory: "3Gi"}
jvmOpts: "-XX:+UseG1GC -XX:MaxRAMPercentage=60"
# Required defaults for the linter
redis:
  url: "redis://redis-master:6379"
kafka:
  bootstrapServers: "kafka.payment.svc.cluster.local:9092"
keda:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 15
  cooldownPeriod: 300
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 45
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.payment.svc.cluster.local:9092
        consumerGroup: payment.psp.result.consumer
        topic: payment.psp.results
        lagThreshold: "5000"
nodeSelector:
  pool: central
serviceMonitor:
  enabled: false
  path: /actuator/prometheus
  interval: 15s
  scrapeTimeout: 10s
  scheme: http
  labels:
    release: prometheus-stack
