server:
  port: 8080

spring:
  application:
    name: payment-central-relay
  lifecycle:
    timeout-per-shutdown-phase: 45s
  jackson:
    time-zone: UTC
  datasource:

management:
  server:
    port: 9000
  health:
    probes:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
      show-details: always
  data:
    redis:
      timeout: 10s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 5000ms

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dogancaglar.common.db.entity
  type-handlers-package: com.dogancaglar.common.db.typehandler

outbox-relay:

app:
  datasource:
    central-outbox:
      driver-class-name: org.postgresql.Driver
    maintenance:
      driver-class-name: org.postgresql.Driver
