{{- if (and .Values.keda (default false .Values.keda.enabled)) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "payment-consumers.fullname" . }}-scaler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment-consumers.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "payment-consumers.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount | default 1 }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default 6 }}
  pollingInterval: {{ .Values.keda.pollingInterval | default 15 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        {{- toYaml .Values.keda.behavior | nindent 8 }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}
  {{- end }}