spring:
  profile: "local"

paymentService:
  image:
    repository: "dcaglar1987/payment-service"
    tag: "latest"
    pullPolicy: "Always"
  jvmOpts: "-Xmx512m"
  resources:
    requests: {cpu: "100m", memory: "256Mi"}
    limits: {cpu: "500m", memory: "512Mi"}

redis:
  url: "redis://localhost:6379"

keda:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers: []
  behavior: {}

topologySpreadConstraints: []

serviceMonitor:
  enabled: false
  path: /actuator/prometheus
  interval: 15s
  scrapeTimeout: 10s
  scheme: http
  labels:
    release: prometheus-stack

service:
  type: ClusterIP
  port: 8080
  portName: http


ingress:
  enabled: false
  className: "nginx"
  host: ""
  paths:
    - path: /
      pathType: Prefix