spring:
  profile: "azure"
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app: payment-edge-workers
runPrivilegeGrantJob: true
keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
        metricName: kube_pod_info
        query: sum(kube_statefulset_replicas{statefulset="payment-edge-cell"})
        threshold: "1"
edgeWorker:
  image:
    pullPolicy: Always
  resources:
    requests: {cpu: "1000m", memory: "1Gi"}
    limits: {cpu: "2000m", memory: "2Gi"}
  jvmOpts: >-
    -XX:+UseG1GC -XX:+AlwaysActAsServerClassMachine -XX:+UseStringDeduplication -XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=60 -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=128m -XX:ThreadStackSize=512 -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=30
service:
  type: ClusterIP
  port: 8080
  portName: http
nodeSelector:
  pool: edge
redis:
  url: redis://redis-master:6379
kafka:
  bootstrapServers: kafka.payment.svc.cluster.local:9092
postgresExporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
config:
  KEYCLOAK_ISSUER_URL: "http://keycloak.payment.svc.cluster.local:8080/realms/ecommerce-platform"
  CENTRAL_DB_URL: "jdbc:postgresql://central-db-postgresql.payment.svc.cluster.local:5432/central-db?options=-c%20timezone=UTC"
  EDGE_DB_NAME: "edge-db"
  CENTRAL_DB_NAME: "central-db"
serviceMonitor:
  enabled: false
