package com.dogancaglar.paymentservice.seed

import com.dogancaglar.paymentservice.domain.model.account.Address
import com.dogancaglar.paymentservice.domain.model.account.MerchantAccount
import com.dogancaglar.paymentservice.domain.model.account.PlatformAccount
import com.dogancaglar.paymentservice.domain.model.account.PlatformFee
import com.dogancaglar.paymentservice.domain.model.account.SellerAccount
import com.dogancaglar.paymentservice.domain.model.common.Amount
import com.dogancaglar.paymentservice.domain.model.common.Currency
import com.dogancaglar.paymentservice.domain.model.ledger.LedgerAccount
import com.fasterxml.jackson.databind.ObjectMapper
import java.io.File

/**
 * Generates the central-db account seed (`charts/central-db/db/accounts-seed.sql`) from
 * `charts/central-db/seed/merchants.json` (see MerchantSeed).
 *
 * The rows come from the domain's own account generation, so the seed always has exactly the ledger
 * accounts the code expects: the platform's per currency, every merchant's, and every seller's.
 *
 * Regenerate after changing merchants.json:
 *   mvn -pl payment-consumers -am test -Dtest=AccountSeedFileTest -Dseed.regenerate=true -Dsurefire.failIfNoSpecifiedTests=false
 * Paths are relative to the payment-consumers module (the test's working directory).
 */
object AccountSeedGenerator {

    val seedFile = File("../charts/central-db/db/accounts-seed.sql")

    private val json = ObjectMapper()

    fun generate(seed: List<MerchantSeed>): String {
        val merchants = mutableListOf<MerchantAccount>()
        val sellersByMerchant = LinkedHashMap<String, List<SellerAccount>>()
        for (m in seed) {
            val currency = Currency(m.currency)
            val merchant = MerchantAccount.createNew(
                accountCode = m.merchantAccount,
                legalName = m.legalName,
                address = Address.of(m.line1, null, m.city, m.postalCode, m.country),
                industry = m.industry,
                currency = currency,
                platformFee = PlatformFee.of(feeAmount(m.platformFeeFixed, currency), m.platformFeeBps),
                isAutoCaptured = m.autoCaptured,
                isAutoSettled = m.autoSettled
            )
            val sellers = mutableListOf<SellerAccount>()
            for (sellerCode in m.sellers) {
                sellers.add(SellerAccount.createNew(sellerCode, merchant.accountCode))
            }
            merchants.add(merchant)
            sellersByMerchant[merchant.accountCode] = sellers
        }

        val sql = StringBuilder()
        sql.append(
            "-- GENERATED by AccountSeedGenerator from charts/central-db/seed/merchants.json. Do not edit by hand.\n"
        )

        // the platform and its ledger accounts, once per currency the merchants use
        val platform = PlatformAccount.createNew()
        sql.append(platformRow(platform))
        val currencies = LinkedHashSet<Currency>()
        for (merchant in merchants) {
            currencies.add(merchant.currency)
        }
        for (currency in currencies) {
            for (ledgerAccount in platform.ledgerAccounts(currency)) {
                sql.append(ledgerRow(ledgerAccount))
            }
        }

        // each merchant, its ledger accounts, then each seller and its ledger accounts (parents first)
        for (merchant in merchants) {
            sql.append(merchantRow(merchant))
            for (ledgerAccount in merchant.ledgerAccounts()) {
                sql.append(ledgerRow(ledgerAccount))
            }
            for (seller in sellersByMerchant.getValue(merchant.accountCode)) {
                sql.append(sellerRow(seller))
                for (ledgerAccount in seller.ledgerAccounts(merchant)) {
                    sql.append(ledgerRow(ledgerAccount))
                }
            }
        }
        return sql.toString()
    }

    @JvmStatic
    fun main(args: Array<String>) {
        seedFile.writeText(generate(MerchantSeed.read(MerchantSeed.file.readText())))
        println("wrote ${seedFile.canonicalPath}")
    }

    private fun feeAmount(quantity: Long, currency: Currency): Amount {
        if (quantity == 0L) {
            return Amount.zero(currency)
        }
        return Amount.of(quantity, currency)
    }

    private fun platformRow(platform: PlatformAccount): String =
        insert(platform.accountCode, "PLATFORM", platform.status.name, null, null, null, null, null, null, null, null)

    private fun merchantRow(m: MerchantAccount): String {
        val profile = LinkedHashMap<String, Any?>()
        profile["legalName"] = m.legalName
        val address = LinkedHashMap<String, Any?>()
        address["line1"] = m.address.line1
        address["line2"] = m.address.line2
        address["city"] = m.address.city
        address["postalCode"] = m.address.postalCode
        address["country"] = m.address.country
        profile["address"] = address
        profile["industry"] = m.industry
        return insert(
            m.accountCode, "MERCHANT", m.status.name, null, null, m.currency.currencyCode,
            m.isAutoCaptured.toString(), m.isAutoSettled.toString(),
            m.platformFee.fixed.quantity.toString(), m.platformFee.basisPoints.toString(),
            json.writeValueAsString(profile)
        )
    }

    private fun sellerRow(s: SellerAccount): String =
        insert(s.accountCode, "SELLER", s.status.name, s.masterAccountCode, null, null, null, null, null, null, null)

    private fun ledgerRow(l: LedgerAccount): String {
        // the owner row: the seller for seller accounts, otherwise the merchant or GLOBAL
        val parent = l.sellerCode ?: l.ownerCode
        return insert(l.accountCode, "LEDGER", l.status.name, parent, l.type.name, l.currency.currencyCode, null, null, null, null, null)
    }

    private fun insert(
        code: String,
        kind: String,
        status: String,
        parent: String?,
        ledgerType: String?,
        currency: String?,
        autoCaptured: String?,
        autoSettled: String?,
        feeFixed: String?,
        feeBps: String?,
        profileJson: String?
    ): String =
        "INSERT INTO accounts (account_code, kind, status, parent_code, ledger_type, currency, is_auto_captured, " +
            "is_auto_settled, platform_fee_fixed, platform_fee_bps, profile) VALUES (" +
            "${text(code)}, ${text(kind)}, ${text(status)}, ${text(parent)}, ${text(ledgerType)}, ${text(currency)}, " +
            "${raw(autoCaptured)}, ${raw(autoSettled)}, ${raw(feeFixed)}, ${raw(feeBps)}, ${jsonb(profileJson)});\n"

    private fun text(value: String?): String {
        if (value == null) {
            return "NULL"
        }
        return "'" + value.replace("'", "''") + "'"
    }

    private fun raw(value: String?): String = value ?: "NULL"

    private fun jsonb(value: String?): String {
        if (value == null) {
            return "NULL"
        }
        return text(value) + "::jsonb"
    }
}
