apiVersion: v1
kind: Secret
metadata:
  name: central-db-credentials
type: Opaque
stringData:
  PAYMENT_SERVICE_POSTHOG_TRACES_API_TOKEN: {{ .Values.PAYMENT_SERVICE_POSTHOG_TRACES_API_TOKEN}}
  CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME: {{ .Values.CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME }}
  CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD: {{ .Values.CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD }}
  CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME: {{ .Values.CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME }}
  CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD: {{ .Values.CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD }}
  CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{ .Values.CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME }}
  CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{ .Values.CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD }}
  CENTRAL_DB_DUTY_USERNAME: {{ .Values.CENTRAL_DB_DUTY_USERNAME }}
  CENTRAL_DB_DUTY_PASSWORD: {{ .Values.CENTRAL_DB_DUTY_PASSWORD }}
  CENTRAL_DB_MAINTENANCE_USERNAME: {{ .Values.CENTRAL_DB_MAINTENANCE_USERNAME }}
  CENTRAL_DB_MAINTENANCE_PASSWORD: {{ .Values.CENTRAL_DB_MAINTENANCE_PASSWORD }}
  CENTRAL_DB_POSTGRES_PASSWORD: {{ .Values.CENTRAL_DB_POSTGRES_PASSWORD }}



