apiVersion: v1
kind: Secret
metadata:
  name: edge-cell-credentials
type: Opaque
stringData:
  EDGE_DB_PAYMENT_SERVICE_USERNAME: {{ .Values.EDGE_DB_PAYMENT_SERVICE_USERNAME }}
  EDGE_DB_PAYMENT_SERVICE_PASSWORD: {{ .Values.EDGE_DB_PAYMENT_SERVICE_PASSWORD }}
  EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{ .Values.EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME }}
  EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{ .Values.EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD }}
  EDGE_DB_DUTY_USERNAME: {{ .Values.EDGE_DB_DUTY_USERNAME }}
  EDGE_DB_DUTY_PASSWORD: {{ .Values.EDGE_DB_DUTY_PASSWORD }}
  EDGE_DB_MAINTENANCE_USERNAME: {{ .Values.EDGE_DB_MAINTENANCE_USERNAME }}
  EDGE_DB_MAINTENANCE_PASSWORD: {{ .Values.EDGE_DB_MAINTENANCE_PASSWORD }}
  EDGE_DB_POSTGRES_PASSWORD: {{ .Values.EDGE_DB_POSTGRES_PASSWORD }}
  # Stripe secret test key, used when paymentService.pspGatewayType=STRIPE (from edge-cell-sops-secrets.yaml)
  STRIPE_API_KEY: {{ .Values.STRIPE_API_KEY | default "" | quote }}