{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "payment-edge-cell.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "payment-edge-cell.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - http:
        paths:
          # 1. Main Business API Routing
          - path: {{ .Values.ingress.appPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.ingress.appPort }}

          # 2. Management / Health Routing
          - path: {{ .Values.ingress.healthPath }}
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.ingress.healthPort }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}