apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payment-edge-cell.fullname" . }}
  labels:
    {{- include "payment-edge-cell.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "payment-edge-cell.fullname" . }}-headless
  updateStrategy:
    type: RollingUpdate
  replicas: {{ if (and .Values.keda (default false .Values.keda.enabled)) }}{{ .Values.keda.minReplicaCount | default 1 }}{{ else }}1{{ end }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ include "payment-edge-cell.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-edge-cell.fullname" . }}
      annotations:
        rollout/reboot: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 120
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      initContainers:
        - name: edge-db
          image: postgres:15
          restartPolicy: Always   # <--- K8s 1.28
          volumeMounts:
            - name: db-init-scripts
              mountPath: /docker-entrypoint-initdb.d

          envFrom:
            - configMapRef:
                name: edge-cell-config
          env:
            - name: POSTGRES_DB
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_NAME}}
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_POSTGRES_PASSWORD}}
            - name: EDGE_DB_PAYMENT_SERVICE_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_USERNAME}}
            - name: EDGE_DB_PAYMENT_SERVICE_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_PASSWORD}}

            - name: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME}}
            - name: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD}}
            - name: EDGE_DB_DUTY_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_DUTY_USERNAME}}
            - name: EDGE_DB_DUTY_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_DUTY_PASSWORD}}
            - name: EDGE_DB_MAINTENANCE_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_MAINTENANCE_USERNAME}}
            - name: EDGE_DB_MAINTENANCE_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_MAINTENANCE_PASSWORD}}

          args: ["-c", "listen_addresses=*"]
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 15
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 3
        - name: liquibase-migration
          image: liquibase/liquibase:4.24.0
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_URL}}
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_USERNAME}}
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_PASSWORD}}
          args: ["--search-path=/shared-workspace", "update", "--changelog-file=changelog.edge.xml"]

          volumeMounts:
            - name: liquibase-workspace
              mountPath: /shared-workspace
      containers:
        - name: payment-service
          image: "{{ .Values.paymentService.image.repository }}:{{ .Values.paymentService.image.tag }}"
          imagePullPolicy: {{.Values.paymentService.image.pullPolicy | default "Always"}}
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          envFrom:
            - configMapRef:
                name: edge-cell-config
            - secretRef:
                name: edge-cell-credentials
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.paymentService.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile | default "local" }}"
            - name: SPRING_DATA_REDIS_URL
              value: "{{ .Values.redis.url | default "redis://localhost:6379" }}"
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: edge-cell-config
                  key: MANAGEMENT_OTLP_TRACING_ENDPOINT
            - name: POSTGRES_DB
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_NAME}}
          startupProbe:
            httpGet: {path: /actuator/health/liveness, port: management}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: management}
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: management}
            periodSeconds: 15
            failureThreshold: 4
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.paymentService.resources | nindent 12}}
      volumes:
        - name: db-init-scripts
          secret:
            secretName: edge-db-init-secret
        - name: liquibase-workspace
          configMap:
            name: edge-db-changelog-configmap
